import { useState } from 'react';
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import styled from 'styled-components'

export default function Home() {
  const [words, setWord] = useState([
    {
      id: 1,
      word: 'Hola',
      translation: 'Hello'
    }
  ])
  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const onSubmit = data => console.log(data);
  console.log(watch("new-dictionary-work")); // watch input value by passing the name of it

  return (
    <>
      <Head>
        <title>Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Dictionary</h1>

        <form onSubmit={handleSubmit(onSubmit)}>
          <p>Add Word</p>
          <label>
            <input placeholder='New Word' {...register("new-dictionary-work", { required: true })} />
            <p>{errors.exampleRequired && <span>This field is required</span>}</p>
          </label>

          <label>
            <input placeholder='Translation' {...register("new-dictionary-work", { required: true })} />
            <p>{errors.exampleRequired && <span>This field is required</span>}</p>
          </label>
          
          <input type="submit" />
        </form>

        {words.map(word => {
            return (
            <details key={word.id}>
              <summary>{word.word}</summary>
              Translation: {word.translation}
            </details>
          )}
        )}
      </main>

      <footer>
      
      </footer>
    </>
  )
}
